image:
  repository: ""  # Docker image repository
  tag: ""        # Docker image tag
  pullPolicy: IfNotPresent

hostname: ""  # Application hostname for ingress

config:
  apiUrl: ""     # API URL
  fmKey: ""      # Feature Management key
  authUrl: ""    # Auth service URL

ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

replicaCount: 1 